org.gradle.jvmargs=-Xmx1024m -XX:+UseSerialGC -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx512m -XX:+UseSerialGC
org.gradle.java.home=C:/Users/shash/.jdk/jdk-17.0.20.1+1
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
kotlin.code.style=official
org.gradle.parallel=false
